export enum StoryActionType {
    LOADING = 'LOADING',
    GET_STORIES = 'GET_STORIES',
    GET_STORY = 'GET_STORY',
    GET_COMMENT = 'GET_COMMENT',
    UPDATE_COMMENTS = 'UPDATE_COMMENTS',
    COMMENTS_LOADING = 'COMMENTS_LOADING',
    ERROR = 'ERROR',
};
